Raise maxplayers limit to 123
123 is the limit before the scoreboard shows each player as `Lost Connection...`;
 119 was the maximum without raising PROPINDEX_NUMBITS to 14;
  Not sure what the limit for 13 bits is.
 249 is the max before the server can't be created;
  Host_Error: SV_CreateBaseline: SendTable_Encode returned false
tf_hud_passtime.cpp code had to be commented since it caused crashes on startup with more than 33 maxplayers.