fix a compile error caused by using -> on a non-pointer
I'm not sure if this will compile on windows, so *maybe* we should add a
ifdef check for linux. But, this should be correct.
/src/src/public/gcsdk/msgprotobuf.h:383:8: error: base operand of '->' has non-pointer type 'CMsgProtoBufHeader'
  383 |   Hdr()->set_client_session_id( nSessionIDClient );
      |        ^~